# Generated by Django 3.2.18 on 2023-05-01 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_tic_turn', models.PositiveIntegerField(default=1)),
                ('game_time', models.FloatField(blank=True, null=True)),
                ('game_outcome', models.CharField(choices=[('win', 'Win'), ('lose', 'Lose'), ('draw', 'Draw'), ('going', 'On-Going')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('grid_size', models.PositiveIntegerField(default=3)),
                ('game_variation', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('realname', models.CharField(max_length=255)),
                ('total_games_played', models.IntegerField(default=0)),
                ('total_games_won', models.IntegerField(default=0)),
                ('total_games_lost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('move', models.CharField(max_length=10)),
                ('piece', models.CharField(default='X', max_length=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tictactoe.game')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='tac_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tac_games', to='tictactoe.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='tic_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tic_games', to='tictactoe.player'),
        ),
    ]
